BeginPackage["ConnorGray`Organizer`Errors`", {
	"Wolfram`ErrorTools`"
}]

OrganizerError::usage = "Tag used in Failure[..] objects generated by Organizer"

Begin["`Private`"]


CreateErrorType[OrganizerError, {}]


End[]

EndPackage[]